version: '3.4'

services:
 database:
   image: "mcr.microsoft.com/mssql/server:2017-latest"
   container_name: dev_age-tur_sql
   environment:
     SA_PASSWORD : admin*123
     ACCEPT_EULA: "Y"
   ports:
    - "1433:1433"

 age-tur.api:
   image: ${DOCKER_REGISTRY-}ageturapi
   ports:
    - 5001:443
    - 5000:80
   build:
     context: .
     dockerfile: Age-Tur.Api/Dockerfile
   environment:
    - SEED=true
    - 'ConnectionStrings__DbConn=Data Source=127.0.0.1;Initial Catalog=Age-TurApi;User Id=sa;Password=admin*123' 
   depends_on:
     - database
